### ISSUE TITLE
AutoDB not good with Aux

### ISSUE THREAD

**Issue by akidraham** [refaim/AutoDB2#1] opened 2023-03-13 17:09 UTC
Hi, first thing first such good qol addon, my english is quite bad

Problem:
If i enable the AutoDB addon it makes the aux addon throw up errors, i use aux from this [link](https://github.com/shirsig/aux-addon-vanilla)
  
![WoW_Onvq7NZNnZ](https://user-images.githubusercontent.com/102669236/224774014-94c7d192-9364-4cf6-b9f3-bac033987b22.png)

solution disabling the AutoDB addon make the aux errors away
  
Addon list:  
pfUI: enabled
pfUI-CustomMedia: disabled
pfUI-Gryphons: disabled
MrPlow: disabled
ShaguBoP: disabled
HardcoreFilter: enabled
XPerl: enabled
XPerl_RaidHelper: disabled
XPerl_PlayerPet: enabled
XPerl_RaidAdmin: disabled
LunaUnitFrames: disabled
ChatSuey-EditOnTop: enabled
ChatSuey-ChannelLinks: enabled
XPerl_Options: enabled
TurtleChatColors: enabled
TWPowerBar: disabled
SaySapped_Extended: disabled
ShaguTweaks: disabled
AutoBar: enabled
ClassicMouseover: disabled
ClassicSnowFall: disabled
Clique: disabled
MCP: disabled
MasterTradeSkills: enabled
MinimapButtonBag-TurtleWoW: disabled
MobInfo2: disabled
SUCC-bag: disabled
FocusFrame: disabled
Cartographer: disabled
TNE_FiveSec: disabled
aDF: disabled
ManaMinder: disabled
QuickHeal: enabled
SmartHealer: enabled
CatDruidDPS: enabled
CallOfElements: disabled
Egnar: disabled
FonzAppraiser: disabled
ClassIcons: disabled
_LazyPig: enabled
Altoholic: enabled
AtlasLoot: enabled
AutoDB: enabled
BetterCharacterStats: enabled
BetterKeyBinding: enabled
BigWigs: enabled
BonusScanner: enabled
Chronometer: enabled
ShaguDPS: enabled
TWThreat: enabled
ShaguStance: disabled
ShaguJunk: enabled
ShaguChat: disabled
WIM: enabled
VanillaRatingBuster: enabled
SuperIgnore: enabled
SP_SwingTimer: enabled
SortBags: enabled
SmartLoot: enabled
SmartBuff: enabled
Roid-Macros: enabled
RecipeRadar: enabled
ReagentData: enabled
QuestHistory: enabled
QuestAnnouncer: enabled
Possessions: enabled
Outfitter: enabled
Niagara: enabled
MoveAnything: enabled
MouseOverSounds: enabled
MoPGearTooltips: enabled
MissingTradeSkillsList: enabled
FuBar_ToFu: enabled
HealComm: enabled
FishingBuddy: enabled
DruidManaBar: enabled
Decursive: enabled
Clean_Up: disabled
FontScale: enabled
TheoryCraft-Turtle: enabled
AdvancedTradeSkillWindow: enabled

**Comment by refaim** [comment] 2023-05-04 07:01
Hi!

I can't reproduce this error. Could you please:

1) Describe what exactly are you doing in game to make this error appear.
2) Try to enable only aux and AutoDB to see if the issue persists.

**Comment by akidraham** [comment] 2023-05-04 13:20
hi, sorry for the late reply, i will try to reproduce with different character

**Comment by akidraham** [comment] 2023-05-04 13:52
So i test more with different character, with only aux, autodb2, and pfquest (it said dependency missing if not enabled), the error doesnt come up, but with my main, aux throws up error if i enabled autodb2.

1. So what i add into the command are
```
/autodb add mines auto
/autodb add herbs auto
/autodb taxi alliance
```

2. With only autodb2, aux, pfquest, and pfquest-turtle problem doesnt exist
3. With this addons enabled the problem exist, 
Lazypig
AdvancedTradeSkillWindow
Altoholic for Vanilla WoW
Atlas TW Edition
Atlasloot TW Edition
Autobar
AutoDB2
aux
BetterCharacterStats
BetterKeyBinding
Big Wigs Turtle Wow
BonusScanner
CatDruidDPS
Chronometer -Ace2-
Cleanup
Decursive 1.9.8.5
DruidManaBar
Fishing Buddy v0.8.6h
Flyout by luskanek
FontScale Vanilla
FuBar - ToFu
HealComm
Inspector
ImpulseBooster
LFT
Mail
MasterTradeSkills
Mik's Scrolling Battle Text
Mik's Scrolling Battle Text Options
Missing TradeSkills List
MoP Gear Tooltips
MoveAnything!
Niagara -Ace2-
Outfitter
Possessions 2.0.2
QuestAnnouncer -Ace2-
QuestHistory
ReagentData (v2.4.0c)
Recipe Radar
Roid Macros
SmartBuff
SmartLoot
SortBags
SP_SwingTimer
SuperIgnore
TheoryCraft Turtle WoW 1.16.1
Tourguide -Ace2-
Tourguide_Alliance
Tourguide_Horde
Tourguide_Professions
Turtle ChatColors -Gepy-
VanillaRatingBuster
WIM
pfQuest
pfUI
pfUI (TurtleWoW skins)
pfUI (Addon Skinner)
pfUI (Elite Overlay)
ShaguJunk
TW Threatmeter
ShaguDPS

but if i disabled AutoDB2 the problems are gone, maybe there's something error with some addon enabled? any pointer?

will try to enable one by one, 
disabled all with only autodb2, aux, pfquest, and pfquest-turtle, then enabled 
pfUI
open aux, the error pops up 
the error keeps happening even if i didn't add mines auto herbs auto and taxi alliance

**Comment by akidraham** [comment] 2023-05-04 14:13
![WoW_BH18kXiLwk](https://user-images.githubusercontent.com/102669236/236233992-a1f2634a-5e83-484a-a1ad-8345ca4921d7.png)
![WoW_gsBs2OWTEU](https://user-images.githubusercontent.com/102669236/236234016-2ce82a58-1a88-4bf5-b3ba-d6257fee56e0.png)
![WoW_NIzLWUUULt](https://user-images.githubusercontent.com/102669236/236234036-ef9eae74-2331-4f2e-9da6-e4197e57821e.png)

i'm okay with it tho, as this addon and pfUI such a qol for me, i can disable few things if i have to when i visit AH

**Comment by refaim** [comment] 2023-05-04 18:13
Try the new version please. Should be fixed.

**Comment by akidraham** [comment] 2023-05-06 04:02
with aux, autodb2, pfquest, pfquest-turtle and pfui enabled i still got this error with the new version

```
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\results.lua:430: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\core.lua:29: attempt to index field `table' (a nil value)
ERROR: Interface\AddOns\aux-addon\tabs\search\core.lua:29: attempt to index field `table' (a nil value)
```

already tried clearing wtf for that throwaway character and wdb deleted

![WoW_oPWfMIDMCn](https://user-images.githubusercontent.com/102669236/236598885-cdf71482-38e6-41d7-a3a1-e68043848c61.png)

**Comment by shagu** [comment] 2023-06-24 12:19
Greetings,
I have reproduced the same. It also breaks DPSMate (Dock) integration in pfUI for some reason.
I went through your code and it now becomes very weird:

I started deleting one line after the other, to see where it could have potential clashes with pfUI, pfQuest, DPSMate and/or Aux-Addon. I was deleting more and more. In the end, both files (helpers.lua and AutoDB2.lua) were **empty**.
So I deleted both .lua files from the .toc file. And still, DPSMate integration broken and aux-addon is spitting errors.

So with only the `.toc` file left, I started removing lines there, and it turns out, that the errors stop as soon as I remove the line with:
```
## Dependencies: pfQuest
```
So I restored all files and have everything 100% as in your git, with only the Dependency line removed and I now can no longer reproduce any error. I have absolutely no clue what is happening there. Is there some kind of client builtin dependency verifier that only allows addons with the same name-prefix to depend on another? I have no idea.

But I wanted to share that with you.

***Edit**: My setup was Turtle-Wow client, with the following addons: AutoDB2, aux-addon, DPSMate, pfUI, pfQuest, pfQuest-turtle. All installed addons were the latest git versions.*

**Comment by shagu** [comment] 2023-06-24 14:26
I think i got it now. AutoDB2 starts before aux-addon (due to the naming order).
As it has a dependency on pfQuest it makes pfQuest load as early.
This also makes pfUI load right before, because pfQuest has an optional dependency on it.
That dependency tree made pfUI load before the other addons got loaded.

The outcome of this is, that pfUI tries to access a frame of DPSMate, as soon as it gets loaded,
but this time, the frame doesn't exist at that point. That is fixed via: DPSMate: https://github.com/shagu/pfUI/commit/7f9348868bde44c0001fe1b0fbfddfd0c613a3b5

The other is, that aux-addon doesn't like it, if the global UI-Scale gets changed during its
initialization, which is what pfUI was doing. That one is fixed via: https://github.com/shagu/pfUI/commit/41acda2c029e4e289ae4464f54cdc67097951f6a

So, it wasn't the fault of AutoDB2, it just made those two problems visible by changing the known boot oder of pfUI and pfQuest. I think this ticket can be closed.

**Comment by refaim** [comment] 2023-06-24 14:56
@shagu Thank you for such a detailed investigation and fixing the issue from your side! 

Are you sure that this ticket should be closed? While AutoDB2 accidentally helped in uncovering two bugs, it seems like forcing pfQuest and pfUI to load early might be excessive. 

Indeed, AutoDB2 relies on pfQuest, but I guess it's easy to dynamically detect the presence and readiness of pfQuest during runtime instead of relying on a TOC-file dependency.

**Comment by shagu** [comment] 2023-06-24 16:21
If I were you, I wouldn't have it depend on pfQuest, as it doesn't depend on any of the internal pfQuest/pfUI API directly. It would also be a useful addon for non-pfQuest users to autorun other Slash Commands aswell. But that is up to you, what ever you consider the goal and use cases for the addon.

**Closed as completed** 2023-10-05 15:52 UTC
Labels: bug, question
